language: node_js
node_js:
  - node
  - 10
  - 8
cache: npm
install:
  - npm install
script:
  - npm run test
  - codecov
branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
